### PR TITLE
fixed JSON Pointer representation rule

### PR DESCRIPTION
**Pull request by yacchi**
Can not resolve parameter object of 'ref' and 'name' are different.

The OAS2 Spec uses a JSON Pointer, so this has been fixed.
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#referenceObject

### CODE REVIEW

**Comment by mristin** [comment]
Hi @yacchi ,
Thank you a lot for this fix! 

I realized only now that we didn't properly set up the continuous integration for this project, which I've just done. Would you mind to rebase your changes on the master branch in order to check that everything works as expected?

**Comment by yacchi** [comment]
Thanks for your quickly action!

I finished to rebase and "precommit" with no errors.
Would you recheck 'pull-req, please?

**Comment by mristin** [comment]
I will release the next patch version now.

**Comment by mristin** [comment]
Hi @yacchi , thanks again for the patch! I have just released the patch version 3.1.4. It should be available on pypi anytime soon.

**Pull request merged**
